apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-duckdb-pvc
  namespace: eta
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
